name: CI/CD Flow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Generate module jars
        run: mvn clean install -DskipTests
      - name: Build & Push Docker VacationCalculateService
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: pycuk2/vacationcalculateservice
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: pycuk2
          password: ${{ secrets.DOCKER_PASSWORD }}